export const allLanguages = [
    { id: 1, name: "JavaScript" },
    { id: 2, name: "TypeScript" },
    { id: 3, name: "Python" },
    { id: 4, name: "Java" },
    { id: 5, name: "C++" },
    { id: 6, name: "C#" },
    { id: 7, name: "Go" },
    { id: 8, name: "Ruby" },
    { id: 9, name: "PHP" },
    { id: 10, name: "Swift" },
    { id: 11, name: "Kotlin" },
    { id: 12, name: "Rust" },
    { id: 13, name: "Scala" },
    { id: 14, name: "Dart" },
    { id: 15, name: "Perl" },
    { id: 16, name: "Elixir" },
    { id: 17, name: "Flutter" },
    { id: 18, name: "React" },
    { id: 19, name: "Next.js" },
    { id: 20, name: "Vue.js" },
    { id: 21, name: "Nuxt.js" },
    { id: 22, name: "Angular" },
    { id: 23, name: "Svelte" },
    { id: 24, name: "Node.js" },
    { id: 25, name: "NestJS" },
    { id: 26, name: "Express" },
    { id: 27, name: "Laravel" },
    { id: 28, name: "Symfony" },
    { id: 29, name: "Spring Boot" },
    { id: 30, name: ".NET" },
    { id: 31, name: "React Native"},
];
  