export const projects = [
    {
        "id": 1,
        "user_id": 1,
        "name": "Project 1",
        "link": "https://www.google.com",
        "file": null,
    },
    {
        "id": 2,
        "user_id": 1,
        "name": "Project 2",
        "link": "https://www.google.com",
        "file": null,
    },
    {
        "id": 3,
        "user_id": 1,
        "name": "Project 3",
        "link": "https://www.google.com",
        "file": null,
    },
    {
        "id": 4,
        "user_id": 1,
        "name": "Project 4",
        "link": "https://www.google.com",
        "file": null,
    },
    {
        "id": 5,
        "user_id": 1,
        "name": "Project 5",
        "link": "https://www.google.com",
        "file": null,
    },
    {
        "id": 6,
        "user_id": 1,
        "name": "Project 6",
        "link": "https://www.google.com",
        "file": null,
    },
    {
        "id": 7,
        "user_id": 1,
        "name": "Project 7",
        "link": "https://www.google.com",
        "file": null,
    },
    {
        "id": 8,
        "user_id": 1,
        "name": "Project 8",
        "link": "https://www.google.com",
        "file": null,
    },
    {
        "id": 9,
        "user_id": 1,
        "name": "Project 9",
        "link": "https://www.google.com",
        "file": null,
    },
];