"use client"

import { Ubuntu } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
// import { Metadata } from "next";

const ubuntuFont = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "700"],
});


// export const metadata: Metadata = {
//   title: "TalentHub",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <title>TalentHub</title>
        
      </head>
      <body
        className={`${ubuntuFont.className} bg-[#E8E8E8]` }
      >
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
